### ISSUE TITLE
Getting error after importing project

### ISSUE THREAD

**Issue by jahanzeb-j** [udacity/ud851-Exercises#2] opened 2016-12-02 18:41 UTC
I am getting this error after importing the project .
Error: com.android.builder.internal.aapt.AaptException: Failed to crunch file C:\Users\...\Desktop\ud851-Exercises-student_2\ud851-Exercises-student\Lesson02-GitHub-Repo-Search\T02.01-Exercise-CreateLayout\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\24.2.1\res\drawable-hdpi-v4\abc_ic_star_half_black_48dp.png 
into
 C:\Users\...\Desktop\ud851-Exercises-student_2\ud851-Exercises-student\Lesson02-GitHub-Repo-Search\T02.01-Exercise-CreateLayout\app\build\intermediates\res\merged\debug\drawable-hdpi-v4\abc_ic_star_half_black_48dp.png

**Comment by michaelhiatt** [comment] 2016-12-08 05:07
I experienced the same issue and found on the udacity forums a solution that involved moving the project folder closer to the root directory (the filepath was way too long).

Hope this helps and best of luck.

**Comment by JeremySilverTongue** [comment] 2016-12-14 07:15
Dupe of https://github.com/udacity/ud851-Exercises/issues/4

**Closed as completed by JeremySilverTongue** 2016-12-14 07:15 UTC
Labels: duplicate
