### ISSUE TITLE
Error:com.android.builder.internal.aapt.AaptException: Failed to crunch file 

### ISSUE THREAD

**Issue by jeonjuok** [udacity/ud851-Exercises#3] opened 2016-12-03 03:17 UTC
Error:com.android.builder.internal.aapt.AaptException: Failed to crunch file C:\Users\jason\AndroidStudioProjects\ud851-Exercises-student\ud851-Exercises-student\Lesson01-Favorite-Toys\T01.03-Solution-AddScrolling\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\24.1.1\res\drawable-mdpi-v4\abc_btn_switch_to_on_mtrl_00012.9.png into C:\Users\jason\AndroidStudioProjects\ud851-Exercises-student\ud851-Exercises-student\Lesson01-Favorite-Toys\T01.03-Solution-AddScrolling\app\build\intermediates\res\merged\debug\drawable-mdpi-v4\abc_btn_switch_to_on_mtrl_00012.9.png

**Comment by JeremySilverTongue** [comment] 2016-12-14 07:15
Dupe of https://github.com/udacity/ud851-Exercises/issues/4

**Closed as completed by JeremySilverTongue** 2016-12-14 07:15 UTC
Labels: duplicate
